"""
Cognithor DeepResearch Agent v1.0
=================================
Perplexity-style relentless research loop that never stops
until a high-confidence, cross-verified answer is found.

Integrates with Cognithor's PGE Trinity:
  Planner → Gatekeeper → Executor

This module acts as a specialized Planner sub-agent that the
Gatekeeper can invoke when standard search yields insufficient
confidence.

Architecture inspired by Perplexity's Deep Research:
- Plan-and-execute with iterative refinement
- Multi-source cross-verification
- Confidence scoring with minimum threshold gate
- Automatic query decomposition and expansion
- Source priority hierarchy

Author: Alexander Söllner / Cognithor Project
License: Apache 2.0
"""

from __future__ import annotations

import asyncio
import hashlib
import json
import logging
import time
from abc import ABC, abstractmethod
from dataclasses import dataclass, field
from enum import Enum, auto
from typing import Any, Optional

logger = logging.getLogger("cognithor.deep_research")


# ─────────────────────────────────────────────
# 1. CORE DATA MODELS
# ─────────────────────────────────────────────

class SourceTier(Enum):
    """Source priority hierarchy — higher tier = more trustworthy."""
    OFFICIAL_DOCS = 5       # Official documentation, compatibility matrices
    GITHUB_ISSUES = 4       # Project issues, PRs, release notes
    VERIFIED_COMMUNITY = 3  # Reddit/forum posts with confirmed success
    BLOG_TUTORIAL = 2       # Blog posts, tutorials, guides
    UNVERIFIED = 1          # Random forum posts, no confirmation
    IRRELEVANT = 0          # Off-topic results


class ResearchPhase(Enum):
    """Tracks which phase the research loop is in."""
    QUERY_DECOMPOSITION = auto()
    OFFICIAL_SEARCH = auto()
    GITHUB_DEEP_DIVE = auto()
    COMMUNITY_MINING = auto()
    CROSS_VERIFICATION = auto()
    SYNTHESIS = auto()
    DONE = auto()


class TaskComplexity(Enum):
    """Classifier output for incoming tasks."""
    ROUTINE = auto()        # Well-documented, standard procedure
    MODERATE = auto()       # Some nuance, may need 3-5 searches
    RESEARCH_HEAVY = auto() # Bleeding edge, experimental, poor docs
    FRONTIER = auto()       # Basically nobody has done this yet


@dataclass
class SearchResult:
    """Single search result with metadata and quality scoring."""
    url: str
    title: str
    snippet: str
    full_content: str = ""
    source_tier: SourceTier = SourceTier.UNVERIFIED
    relevance_score: float = 0.0        # 0.0–1.0, LLM-judged
    has_working_solution: bool = False   # Did someone confirm it works?
    solution_steps: list[str] = field(default_factory=list)
    timestamp: str = ""                 # When was this posted?
    sha256: str = ""                    # Content hash for dedup

    def __post_init__(self):
        if self.full_content and not self.sha256:
            self.sha256 = hashlib.sha256(
                self.full_content.encode()
            ).hexdigest()[:16]


@dataclass
class ResearchFinding:
    """A synthesized finding backed by multiple sources."""
    claim: str
    confidence: float  # 0.0–1.0
    supporting_sources: list[SearchResult] = field(default_factory=list)
    contradicting_sources: list[SearchResult] = field(default_factory=list)
    is_verified: bool = False

    @property
    def cross_verified(self) -> bool:
        """A finding is cross-verified if 2+ independent sources agree."""
        unique_domains = set()
        for src in self.supporting_sources:
            domain = src.url.split("/")[2] if "/" in src.url else src.url
            unique_domains.add(domain)
        return len(unique_domains) >= 2


@dataclass
class ResearchPlan:
    """The research strategy generated by query decomposition."""
    original_query: str
    complexity: TaskComplexity
    sub_queries: list[str] = field(default_factory=list)
    search_strategies: list[str] = field(default_factory=list)
    max_search_rounds: int = 25
    min_confidence_threshold: float = 0.75
    current_phase: ResearchPhase = ResearchPhase.QUERY_DECOMPOSITION
    findings: list[ResearchFinding] = field(default_factory=list)
    all_results: list[SearchResult] = field(default_factory=list)
    search_count: int = 0
    started_at: float = field(default_factory=time.time)

    @property
    def best_confidence(self) -> float:
        if not self.findings:
            return 0.0
        return max(f.confidence for f in self.findings)

    @property
    def has_verified_solution(self) -> bool:
        return any(
            f.is_verified and f.confidence >= self.min_confidence_threshold
            for f in self.findings
        )

    @property
    def elapsed_seconds(self) -> float:
        return time.time() - self.started_at


# ─────────────────────────────────────────────
# 2. ABSTRACT INTERFACES (for Cognithor integration)
# ─────────────────────────────────────────────

class SearchProvider(ABC):
    """
    Abstract search interface — implement for your preferred
    search backend (SearXNG, Tavily, Brave, Perplexity API, etc.)
    """

    @abstractmethod
    async def search(self, query: str, max_results: int = 10) -> list[dict]:
        """Returns list of {url, title, snippet}."""
        ...

    @abstractmethod
    async def fetch_page(self, url: str) -> str:
        """Fetches full page content from URL."""
        ...


class LLMProvider(ABC):
    """
    Abstract LLM interface — implement for your preferred
    LLM (Ollama, OpenAI, Anthropic, local model, etc.)
    """

    @abstractmethod
    async def complete(
        self,
        system_prompt: str,
        user_prompt: str,
        temperature: float = 0.3,
    ) -> str:
        """Returns LLM completion text."""
        ...


# ─────────────────────────────────────────────
# 3. TASK COMPLEXITY CLASSIFIER
# ─────────────────────────────────────────────

COMPLEXITY_CLASSIFIER_PROMPT = """You are a task complexity classifier for technical support queries.

Analyze the query and classify it into exactly ONE category:

ROUTINE — Well-documented procedure. Official docs exist, widely done.
  Examples: "install nginx on Ubuntu", "create a Python venv"

MODERATE — Mostly documented but needs some specific configuration.
  Examples: "set up PostgreSQL replication", "configure CUDA for PyTorch"

RESEARCH_HEAVY — Bleeding-edge, experimental, or poorly documented.
  Signals: very new hardware/software, no official support, community workarounds only.
  Examples: "run vLLM on AMD RDNA 4", "use Whisper with RK3588 NPU"

FRONTIER — Almost nobody has successfully done this yet.
  Examples: "run llama.cpp on RISC-V with vector extensions"

Respond with ONLY the category name and a one-line justification.

Query: {query}"""


class TaskComplexityClassifier:
    """Classifies incoming tasks to determine research intensity."""

    def __init__(self, llm: LLMProvider):
        self.llm = llm

    async def classify(self, query: str) -> TaskComplexity:
        response = await self.llm.complete(
            system_prompt="You are a precise classifier. Respond only with the category name and one line of justification.",
            user_prompt=COMPLEXITY_CLASSIFIER_PROMPT.format(query=query),
            temperature=0.1,
        )

        response_upper = response.upper()
        if "FRONTIER" in response_upper:
            return TaskComplexity.FRONTIER
        elif "RESEARCH_HEAVY" in response_upper:
            return TaskComplexity.RESEARCH_HEAVY
        elif "MODERATE" in response_upper:
            return TaskComplexity.MODERATE
        else:
            return TaskComplexity.ROUTINE


# ─────────────────────────────────────────────
# 4. QUERY DECOMPOSER
# ─────────────────────────────────────────────

DECOMPOSER_PROMPT = """You are an expert research query decomposer.

Given a technical query, break it down into a systematic research plan.
Generate search queries in ORDER OF PRIORITY:

1. OFFICIAL sources first (docs, compatibility matrices, release notes)
2. GITHUB sources (issues, PRs, discussions for relevant repos)
3. COMMUNITY sources (Reddit, forums, Stack Overflow, blog posts)
4. LATERAL sources (similar hardware/software that might have workarounds)

For each query, specify:
- The actual search string to use
- Which source tier it targets
- What information we're looking for

CRITICAL: Generate diverse queries. Don't just rephrase the same thing.
Think about what ADJACENT information might help solve the problem.

Example for "run vLLM on AMD 9070 XT":
- "vLLM ROCm RDNA 4 compatibility" → OFFICIAL (does vLLM officially support this?)
- "vllm-project/vllm AMD GPU" site:github.com → GITHUB (any issues/PRs?)
- "9070 XT ROCm version support" → OFFICIAL (which ROCm version works?)
- "vLLM AMD Radeon" reddit → COMMUNITY (has anyone tried this?)
- "7900 XTX vLLM setup guide" → LATERAL (what worked for similar AMD GPU?)
- "RDNA 4 gfx12 ROCm docker" → COMMUNITY (Docker-specific solutions?)
- "pytorch ROCm RDNA 4 compile" → LATERAL (prerequisite: does PyTorch work?)

Respond in JSON format:
{{
  "sub_queries": [
    {{"query": "...", "tier": "OFFICIAL|GITHUB|COMMUNITY|LATERAL", "looking_for": "..."}}
  ],
  "key_unknowns": ["what we don't know yet"],
  "related_technologies": ["tech stack components to investigate"]
}}

Original query: {query}"""


class QueryDecomposer:
    """Breaks down complex queries into systematic search plans."""

    def __init__(self, llm: LLMProvider):
        self.llm = llm

    async def decompose(self, query: str) -> list[dict]:
        response = await self.llm.complete(
            system_prompt="You are a research planning expert. Always respond in valid JSON.",
            user_prompt=DECOMPOSER_PROMPT.format(query=query),
            temperature=0.4,
        )

        try:
            # Strip markdown fences if present
            cleaned = response.strip()
            if cleaned.startswith("```"):
                cleaned = cleaned.split("\n", 1)[1]
            if cleaned.endswith("```"):
                cleaned = cleaned.rsplit("```", 1)[0]
            cleaned = cleaned.strip()

            data = json.loads(cleaned)
            return data.get("sub_queries", [])
        except json.JSONDecodeError:
            logger.warning("Failed to parse decomposition, using fallback")
            return [{"query": query, "tier": "COMMUNITY", "looking_for": "any solution"}]


# ─────────────────────────────────────────────
# 5. RESULT EVALUATOR (the "Confidence Judge")
# ─────────────────────────────────────────────

EVALUATOR_PROMPT = """You are a strict technical solution evaluator.

Given a search result for the query "{query}", evaluate:

1. RELEVANCE (0.0-1.0): Does this directly address the query?
2. ACTIONABILITY (0.0-1.0): Does it contain concrete, executable steps?
3. VERIFICATION (0.0-1.0): Is there evidence this actually works?
   - 1.0 = Author confirms success with exact same setup
   - 0.7 = Author confirms success with similar setup
   - 0.4 = Theoretical/untested suggestion
   - 0.1 = Clearly outdated or different context
4. SOURCE_TIER: OFFICIAL_DOCS | GITHUB_ISSUES | VERIFIED_COMMUNITY | BLOG_TUTORIAL | UNVERIFIED
5. HAS_WORKING_SOLUTION: true/false — Does this contain a confirmed working solution?
6. SOLUTION_STEPS: If there are concrete steps, list them.

Respond in JSON:
{{
  "relevance": 0.0,
  "actionability": 0.0,
  "verification": 0.0,
  "source_tier": "...",
  "has_working_solution": false,
  "solution_steps": [],
  "reasoning": "one line explaining your assessment"
}}

Search result title: {title}
Search result URL: {url}
Content:
{content}"""


class ResultEvaluator:
    """LLM-powered judge that scores search results for quality."""

    def __init__(self, llm: LLMProvider):
        self.llm = llm

    async def evaluate(
        self, query: str, result: SearchResult
    ) -> SearchResult:
        """Evaluates and enriches a SearchResult with quality scores."""
        content_preview = result.full_content[:3000] or result.snippet

        response = await self.llm.complete(
            system_prompt="You are a strict evaluator. Respond only in valid JSON.",
            user_prompt=EVALUATOR_PROMPT.format(
                query=query,
                title=result.title,
                url=result.url,
                content=content_preview,
            ),
            temperature=0.1,
        )

        try:
            cleaned = response.strip()
            if cleaned.startswith("```"):
                cleaned = cleaned.split("\n", 1)[1]
            if cleaned.endswith("```"):
                cleaned = cleaned.rsplit("```", 1)[0]

            scores = json.loads(cleaned.strip())

            # Composite relevance score
            result.relevance_score = (
                scores.get("relevance", 0) * 0.3
                + scores.get("actionability", 0) * 0.3
                + scores.get("verification", 0) * 0.4  # Verification weighted highest
            )

            tier_map = {
                "OFFICIAL_DOCS": SourceTier.OFFICIAL_DOCS,
                "GITHUB_ISSUES": SourceTier.GITHUB_ISSUES,
                "VERIFIED_COMMUNITY": SourceTier.VERIFIED_COMMUNITY,
                "BLOG_TUTORIAL": SourceTier.BLOG_TUTORIAL,
                "UNVERIFIED": SourceTier.UNVERIFIED,
            }
            result.source_tier = tier_map.get(
                scores.get("source_tier", ""), SourceTier.UNVERIFIED
            )
            result.has_working_solution = scores.get("has_working_solution", False)
            result.solution_steps = scores.get("solution_steps", [])

        except (json.JSONDecodeError, KeyError) as e:
            logger.warning(f"Evaluation parse failed: {e}")
            result.relevance_score = 0.2

        return result


# ─────────────────────────────────────────────
# 6. ADAPTIVE QUERY EXPANDER
# ─────────────────────────────────────────────

EXPANDER_PROMPT = """You are a search query strategist.

The original research question is: "{original_query}"

So far, we've done {search_count} searches and our best confidence is {best_confidence:.0%}.

Here's what we've found so far:
{findings_summary}

Here's what we still DON'T know:
{gaps}

Generate 3-5 NEW search queries that:
1. Target the specific gaps we haven't filled
2. Use DIFFERENT keywords and angles than previous searches
3. Try lateral approaches (similar hardware, adjacent projects, workarounds)
4. Include site-specific searches where helpful (github.com, reddit.com)

Previous queries used (DO NOT repeat these):
{previous_queries}

Respond in JSON: {{"new_queries": ["query1", "query2", ...]}}"""


class AdaptiveQueryExpander:
    """Generates new search queries based on what's been found so far."""

    def __init__(self, llm: LLMProvider):
        self.llm = llm

    async def expand(self, plan: ResearchPlan) -> list[str]:
        findings_summary = "\n".join(
            f"- {f.claim} (confidence: {f.confidence:.0%})"
            for f in plan.findings
        ) or "Nothing conclusive yet."

        gaps = self._identify_gaps(plan)

        response = await self.llm.complete(
            system_prompt="You are a creative search strategist. Respond in valid JSON.",
            user_prompt=EXPANDER_PROMPT.format(
                original_query=plan.original_query,
                search_count=plan.search_count,
                best_confidence=plan.best_confidence,
                findings_summary=findings_summary,
                gaps=gaps,
                previous_queries=json.dumps(plan.sub_queries, indent=2),
            ),
            temperature=0.6,  # Higher creativity for diverse queries
        )

        try:
            cleaned = response.strip()
            if cleaned.startswith("```"):
                cleaned = cleaned.split("\n", 1)[1]
            if cleaned.endswith("```"):
                cleaned = cleaned.rsplit("```", 1)[0]
            data = json.loads(cleaned.strip())
            return data.get("new_queries", [])
        except json.JSONDecodeError:
            return []

    def _identify_gaps(self, plan: ResearchPlan) -> str:
        gaps = []
        has_official = any(
            r.source_tier == SourceTier.OFFICIAL_DOCS
            for r in plan.all_results
            if r.relevance_score > 0.5
        )
        has_verified = any(r.has_working_solution for r in plan.all_results)
        has_steps = any(r.solution_steps for r in plan.all_results)

        if not has_official:
            gaps.append("No official documentation found confirming support")
        if not has_verified:
            gaps.append("No verified working solution found from anyone")
        if not has_steps:
            gaps.append("No concrete step-by-step instructions found")
        if not gaps:
            gaps.append("Need cross-verification from additional sources")

        return "\n".join(f"- {g}" for g in gaps)


# ─────────────────────────────────────────────
# 7. SOLUTION SYNTHESIZER
# ─────────────────────────────────────────────

SYNTHESIZER_PROMPT = """You are a technical solution synthesizer.

Original question: {query}

Based on {num_sources} sources searched, here are the findings:

{findings}

Top sources:
{top_sources}

Create a comprehensive answer that:
1. States clearly whether this is CONFIRMED WORKING or EXPERIMENTAL/THEORETICAL
2. Provides step-by-step instructions if available
3. Notes any prerequisites or compatibility requirements
4. Warns about known issues or pitfalls
5. Suggests fallback approaches if the primary solution might fail
6. Cites which sources each claim comes from

If we couldn't find a confirmed solution, be HONEST about that and explain:
- What IS known
- What the most promising approach seems to be
- What specific risks or unknowns remain
- What the user should try first

NEVER fabricate steps. If a step is uncertain, say so explicitly."""


class SolutionSynthesizer:
    """Combines all findings into a final, actionable answer."""

    def __init__(self, llm: LLMProvider):
        self.llm = llm

    async def synthesize(self, plan: ResearchPlan) -> str:
        findings_text = "\n\n".join(
            f"Finding {i+1} (confidence: {f.confidence:.0%}, "
            f"verified: {f.is_verified}, "
            f"cross-verified: {f.cross_verified}):\n{f.claim}"
            for i, f in enumerate(plan.findings)
        )

        top_results = sorted(
            plan.all_results,
            key=lambda r: r.relevance_score,
            reverse=True,
        )[:10]

        top_sources_text = "\n".join(
            f"- [{r.source_tier.name}] {r.title} ({r.url})\n"
            f"  Relevance: {r.relevance_score:.0%} | "
            f"Working solution: {r.has_working_solution}\n"
            f"  Steps: {r.solution_steps[:3] if r.solution_steps else 'None'}"
            for r in top_results
        )

        return await self.llm.complete(
            system_prompt="You are a precise technical writer. Never fabricate information.",
            user_prompt=SYNTHESIZER_PROMPT.format(
                query=plan.original_query,
                num_sources=len(plan.all_results),
                findings=findings_text or "No high-confidence findings yet.",
                top_sources=top_sources_text or "No highly relevant sources found.",
            ),
            temperature=0.2,
        )


# ─────────────────────────────────────────────
# 8. THE MAIN RESEARCH LOOP ENGINE
# ─────────────────────────────────────────────

class DeepResearchAgent:
    """
    The core research engine. Runs a relentless search loop that:
    
    1. Classifies task complexity
    2. Decomposes query into sub-queries
    3. Searches iteratively through source tiers
    4. Evaluates each result for quality/relevance
    5. Expands queries based on gaps found
    6. Cross-verifies findings across sources
    7. Only stops when confidence threshold met OR max rounds hit
    8. Synthesizes final answer with full source attribution
    
    Integrates with Cognithor's PGE Trinity as a specialized
    Planner sub-agent. The Gatekeeper checks the confidence
    score before passing to the Executor.
    """

    def __init__(
        self,
        search: SearchProvider,
        llm: LLMProvider,
        *,
        max_searches: int = 30,
        min_confidence: float = 0.75,
        fetch_full_pages: bool = True,
        progress_callback: Optional[Any] = None,  # async callable
    ):
        self.search = search
        self.llm = llm
        self.max_searches = max_searches
        self.min_confidence = min_confidence
        self.fetch_full_pages = fetch_full_pages
        self.progress_callback = progress_callback

        # Sub-components
        self.classifier = TaskComplexityClassifier(llm)
        self.decomposer = QueryDecomposer(llm)
        self.evaluator = ResultEvaluator(llm)
        self.expander = AdaptiveQueryExpander(llm)
        self.synthesizer = SolutionSynthesizer(llm)

    async def research(self, query: str) -> dict:
        """
        Main entry point. Returns a dict with:
        {
            "answer": str,           # The synthesized answer
            "confidence": float,     # Overall confidence 0.0-1.0
            "verified": bool,        # Whether solution is cross-verified
            "complexity": str,       # Task complexity classification
            "searches_performed": int,
            "sources_found": int,
            "elapsed_seconds": float,
            "findings": [...],       # Detailed findings
            "top_sources": [...]     # Best sources with URLs
        }
        """
        logger.info(f"Starting deep research: {query}")

        # ── Phase 1: Classify complexity ──
        complexity = await self.classifier.classify(query)
        await self._emit_progress(f"Task classified as: {complexity.name}")

        # Adjust parameters based on complexity
        plan = self._create_plan(query, complexity)

        # ── Phase 2: Decompose query ──
        plan.current_phase = ResearchPhase.QUERY_DECOMPOSITION
        sub_queries = await self.decomposer.decompose(query)
        plan.sub_queries = [sq["query"] for sq in sub_queries]
        await self._emit_progress(
            f"Research plan: {len(plan.sub_queries)} initial queries generated"
        )

        # ── Phase 3: THE RELENTLESS LOOP ──
        round_num = 0
        queries_to_run = list(plan.sub_queries)
        seen_urls: set[str] = set()

        while (
            plan.search_count < plan.max_search_rounds
            and not plan.has_verified_solution
            and queries_to_run
        ):
            round_num += 1
            plan.current_phase = self._determine_phase(round_num)

            await self._emit_progress(
                f"Round {round_num} | Phase: {plan.current_phase.name} | "
                f"Searches: {plan.search_count}/{plan.max_search_rounds} | "
                f"Best confidence: {plan.best_confidence:.0%}"
            )

            # Run current batch of queries
            batch = queries_to_run[:3]  # 3 queries per round
            queries_to_run = queries_to_run[3:]

            for q in batch:
                if plan.search_count >= plan.max_search_rounds:
                    break

                raw_results = await self.search.search(q, max_results=8)
                plan.search_count += 1

                for raw in raw_results:
                    url = raw.get("url", "")
                    if url in seen_urls:
                        continue
                    seen_urls.add(url)

                    result = SearchResult(
                        url=url,
                        title=raw.get("title", ""),
                        snippet=raw.get("snippet", ""),
                    )

                    # Fetch full page content for deeper analysis
                    if self.fetch_full_pages:
                        try:
                            result.full_content = await self.search.fetch_page(url)
                        except Exception as e:
                            logger.debug(f"Failed to fetch {url}: {e}")
                            result.full_content = result.snippet

                    # Evaluate quality
                    result = await self.evaluator.evaluate(query, result)
                    plan.all_results.append(result)

                    # If this looks promising, create/update a finding
                    if result.relevance_score >= 0.5:
                        self._update_findings(plan, result)

                    await self._emit_progress(
                        f"  [{result.source_tier.name}] "
                        f"Score: {result.relevance_score:.0%} | "
                        f"Working: {result.has_working_solution} | "
                        f"{result.title[:60]}"
                    )

            # ── Check: Do we have enough? ──
            if plan.has_verified_solution:
                await self._emit_progress(
                    "✅ HIGH-CONFIDENCE VERIFIED SOLUTION FOUND"
                )
                break

            # ── If not, generate new queries based on gaps ──
            if not queries_to_run and plan.search_count < plan.max_search_rounds:
                new_queries = await self.expander.expand(plan)
                if new_queries:
                    queries_to_run.extend(new_queries)
                    plan.sub_queries.extend(new_queries)
                    await self._emit_progress(
                        f"Expanding search: {len(new_queries)} new queries "
                        f"targeting identified gaps"
                    )
                else:
                    await self._emit_progress(
                        "No more expansion queries generated. Synthesizing results."
                    )
                    break

        # ── Phase 4: Cross-verification ──
        plan.current_phase = ResearchPhase.CROSS_VERIFICATION
        self._cross_verify_findings(plan)

        # ── Phase 5: Synthesize final answer ──
        plan.current_phase = ResearchPhase.SYNTHESIS
        answer = await self.synthesizer.synthesize(plan)

        # ── Build result ──
        plan.current_phase = ResearchPhase.DONE
        top_sources = sorted(
            plan.all_results,
            key=lambda r: r.relevance_score,
            reverse=True,
        )[:10]

        result = {
            "answer": answer,
            "confidence": plan.best_confidence,
            "verified": plan.has_verified_solution,
            "complexity": complexity.name,
            "searches_performed": plan.search_count,
            "sources_found": len(plan.all_results),
            "unique_urls": len(seen_urls),
            "elapsed_seconds": plan.elapsed_seconds,
            "findings": [
                {
                    "claim": f.claim,
                    "confidence": f.confidence,
                    "verified": f.is_verified,
                    "cross_verified": f.cross_verified,
                    "num_sources": len(f.supporting_sources),
                }
                for f in plan.findings
            ],
            "top_sources": [
                {
                    "url": s.url,
                    "title": s.title,
                    "tier": s.source_tier.name,
                    "score": s.relevance_score,
                    "has_solution": s.has_working_solution,
                }
                for s in top_sources
            ],
        }

        await self._emit_progress(
            f"Research complete: {plan.search_count} searches, "
            f"{len(plan.all_results)} sources, "
            f"confidence: {plan.best_confidence:.0%}, "
            f"time: {plan.elapsed_seconds:.1f}s"
        )

        return result

    # ── Helper methods ──

    def _create_plan(self, query: str, complexity: TaskComplexity) -> ResearchPlan:
        """Creates research plan with parameters tuned to complexity."""
        params = {
            TaskComplexity.ROUTINE:       (8,  0.8),
            TaskComplexity.MODERATE:       (15, 0.75),
            TaskComplexity.RESEARCH_HEAVY: (25, 0.65),
            TaskComplexity.FRONTIER:       (30, 0.55),
        }
        max_rounds, min_conf = params.get(complexity, (25, 0.7))

        return ResearchPlan(
            original_query=query,
            complexity=complexity,
            max_search_rounds=min(max_rounds, self.max_searches),
            min_confidence_threshold=max(min_conf, self.min_confidence),
        )

    def _determine_phase(self, round_num: int) -> ResearchPhase:
        """Maps round number to research phase."""
        if round_num <= 2:
            return ResearchPhase.OFFICIAL_SEARCH
        elif round_num <= 4:
            return ResearchPhase.GITHUB_DEEP_DIVE
        else:
            return ResearchPhase.COMMUNITY_MINING

    def _update_findings(self, plan: ResearchPlan, result: SearchResult) -> None:
        """Updates or creates findings based on a relevant result."""
        # Check if this result supports an existing finding
        merged = False
        for finding in plan.findings:
            if self._results_agree(finding, result):
                finding.supporting_sources.append(result)
                # Recalculate confidence based on source count and quality
                finding.confidence = self._calculate_finding_confidence(finding)
                if result.has_working_solution:
                    finding.is_verified = True
                merged = True
                break

        if not merged:
            # Create new finding
            finding = ResearchFinding(
                claim=self._extract_claim(result),
                confidence=result.relevance_score * 0.7,  # Single source penalty
                supporting_sources=[result],
                is_verified=result.has_working_solution,
            )
            plan.findings.append(finding)

    def _results_agree(self, finding: ResearchFinding, result: SearchResult) -> bool:
        """
        Checks if a new result agrees with an existing finding.
        Simple heuristic: if solution steps overlap significantly.
        """
        if not finding.supporting_sources:
            return False

        # Check for overlapping solution steps
        existing_steps = set()
        for src in finding.supporting_sources:
            existing_steps.update(s.lower() for s in src.solution_steps)

        new_steps = set(s.lower() for s in result.solution_steps)

        if existing_steps and new_steps:
            overlap = existing_steps & new_steps
            return len(overlap) >= min(1, len(new_steps) // 2)

        return False

    def _calculate_finding_confidence(self, finding: ResearchFinding) -> float:
        """
        Confidence formula:
        - Base: average relevance of supporting sources
        - Boost: +0.1 per additional independent source (capped at +0.3)
        - Boost: +0.15 if cross-verified (2+ domains)
        - Boost: +0.1 if any source is official docs
        - Penalty: -0.1 per contradicting source
        """
        if not finding.supporting_sources:
            return 0.0

        avg_relevance = sum(
            s.relevance_score for s in finding.supporting_sources
        ) / len(finding.supporting_sources)

        # Source count boost (diminishing returns)
        source_boost = min(0.3, (len(finding.supporting_sources) - 1) * 0.1)

        # Cross-verification boost
        cross_boost = 0.15 if finding.cross_verified else 0.0

        # Official source boost
        official_boost = 0.1 if any(
            s.source_tier == SourceTier.OFFICIAL_DOCS
            for s in finding.supporting_sources
        ) else 0.0

        # Contradiction penalty
        contra_penalty = len(finding.contradicting_sources) * 0.1

        confidence = (
            avg_relevance + source_boost + cross_boost + official_boost - contra_penalty
        )
        return max(0.0, min(1.0, confidence))

    def _extract_claim(self, result: SearchResult) -> str:
        """Extracts the core claim/solution from a search result."""
        if result.solution_steps:
            return f"Solution ({len(result.solution_steps)} steps): " + "; ".join(
                result.solution_steps[:3]
            )
        return result.snippet[:200]

    def _cross_verify_findings(self, plan: ResearchPlan) -> None:
        """Final cross-verification pass across all findings."""
        for finding in plan.findings:
            finding.confidence = self._calculate_finding_confidence(finding)
            if finding.cross_verified and finding.confidence >= plan.min_confidence_threshold:
                finding.is_verified = True

    async def _emit_progress(self, message: str) -> None:
        """Sends progress updates via callback."""
        logger.info(message)
        if self.progress_callback:
            try:
                await self.progress_callback(message)
            except Exception:
                pass


# ─────────────────────────────────────────────
# 9. COGNITHOR GATEKEEPER INTEGRATION
# ─────────────────────────────────────────────

class GatekeeperResearchPolicy:
    """
    Policy for Cognithor's Gatekeeper to decide when to
    invoke the DeepResearchAgent vs. standard search.

    Usage in Cognithor's policy engine:
    
        gatekeeper = GatekeeperResearchPolicy(classifier)
        
        if await gatekeeper.needs_deep_research(task):
            result = await deep_research_agent.research(task.query)
            if gatekeeper.result_acceptable(result):
                executor.execute(result["answer"])
            else:
                executor.report_inconclusive(result)
    """

    def __init__(self, classifier: TaskComplexityClassifier):
        self.classifier = classifier

    async def needs_deep_research(self, query: str) -> bool:
        """Returns True if the query needs DeepResearch instead of standard search."""
        complexity = await self.classifier.classify(query)
        return complexity in (TaskComplexity.RESEARCH_HEAVY, TaskComplexity.FRONTIER)

    def result_acceptable(
        self,
        result: dict,
        *,
        min_confidence: float = 0.65,
    ) -> bool:
        """
        Gatekeeper check: Is the research result good enough
        to pass to the Executor for action?
        """
        return (
            result.get("confidence", 0) >= min_confidence
            and result.get("sources_found", 0) >= 2
        )


# ─────────────────────────────────────────────
# 10. EXAMPLE USAGE / QUICK START
# ─────────────────────────────────────────────

"""
Quick start example:

    from cognithor.providers.searxng import SearXNGProvider
    from cognithor.providers.ollama import OllamaProvider

    search = SearXNGProvider(base_url="http://localhost:8080")
    llm = OllamaProvider(model="gemma3:27b")

    agent = DeepResearchAgent(
        search=search,
        llm=llm,
        max_searches=25,
        min_confidence=0.70,
    )

    # Async usage
    result = await agent.research(
        "How to install and run vLLM on AMD Radeon 9070 XT with ROCm"
    )

    print(f"Confidence: {result['confidence']:.0%}")
    print(f"Verified: {result['verified']}")
    print(f"Searches: {result['searches_performed']}")
    print(f"Answer:\n{result['answer']}")

    # Integration with Cognithor Gatekeeper
    gatekeeper = GatekeeperResearchPolicy(
        TaskComplexityClassifier(llm)
    )

    if await gatekeeper.needs_deep_research(query):
        result = await agent.research(query)
        if gatekeeper.result_acceptable(result):
            # Pass to Executor with full confidence
            ...
        else:
            # Report to user: best effort, but not fully verified
            ...
"""
